---
title: "FYP Analysis"
output:
  html_document: default
  pdf_document: default
---
**TODOs**:

- Pay participants, calculate bonuses (including for problems -- see prolific messages), pay again
- chat processing --> output chat, tag, reimport (not for first sample!)
- Actual Bayesian stuff


```{r set-up, include=F}
knitr::opts_chunk$set(echo = FALSE, warning=F, message=F)
options(knitr.table.format = "html")
library(tidyverse)
library(jsonlite)
library(here)
library(rlang)
theme_set(theme_bw())

ParseJSONColumn <- function(x) {
  str_c("[ ", str_c(x, collapse = ",", sep=" "), " ]")  %>% 
    fromJSON(flatten = T)
}

##Data import constants
data_location="data/study1"


date_start=lubridate::ymd('2021-05-04')

image_location="write-ups/images"
```

<!--# Payment

<!-- ```{r} -->

<!-- d.treatments <- read_csv(here(data_location, 'treatments.csv')) %>% rename(treatmentId=`_id`) -->

<!-- d.games <- read_csv(here(data_location, 'games.csv')) %>% -->
<!--   select(gameId=`_id`, treatmentId, playerIds) %>% -->
<!--   left_join(d.treatments) %>% -->
<!--   mutate(playerIds=str_split(playerIds,",")) %>% -->
<!--   unnest(playerIds) %>% -->
<!--   select(playerId=playerIds, name) -->

<!-- d.players <- read_csv(here(data_location, 'players.csv')) %>% -->
<!--   rename(playerId=`_id`) %>% -->
<!--   left_join(d.games) %>% -->
<!--   select(data.bonus, playerId,id,data.bonus,name) %>% -->
<!--     filter(!is.na(name)) %>% -->
<!--   mutate(pc_bonus=case_when( -->
<!--     name=="fourRotate" ~ 3, -->
<!--     name=="threeRotate" ~ 1.5, -->
<!--     T ~ 0 -->
<!--   )) %>% -->
<!--   mutate(bonus=round(data.bonus+pc_bonus,2), -->
<!--          cost=round(bonus*4/3,2)) %>% write_csv(here(data_location, "player_payments.csv")) %>% select(id,bonus) %>% write_csv(here(data_location,"for_prolific.csv")) -->
<!-- ``` -->

# Pre-process

```{r}
d.games <- read_csv(here(data_location, 'games.csv')) %>% 
  rename(gameId = `_id`) %>% 
    filter(createdAt >= date_start)

d.chat.raw <- read_csv(here(data_location, 'rounds.csv'), guess_max=10000) %>%
  filter(createdAt >= date_start) %>%
  mutate(data.chat = ifelse(is.na(data.chat), '{}', data.chat)) %>%
  rename(row_id = `_id`) %>%
  mutate(data.chat = map(data.chat, .f = ParseJSONColumn)) %>%
  unnest(data.chat) %>%
  select(-data.target, -ends_with('response'), -ends_with('_correct'), -ends_with('time')) %>%
  rename_with(~ gsub("data.", "", .x, fixed = TRUE)) 

d.round_results.raw <- read_csv(here(data_location,'rounds.csv'),guess_max=10000) %>% 
  filter(createdAt >= date_start) %>% 
  rename_with(~ gsub("data.", "", .x, fixed = TRUE)) %>% 
  rename_with ( ~ gsub("room", "player", .x, fixed=T)) %>% 
    rename_with ( ~ gsub("player", "player_", .x, fixed=T)) %>% 
    rename_with ( ~ gsub("correct", "_correct", .x, fixed=T)) %>% 
    rename_with ( ~ gsub("response", "_response", .x, fixed=T)) %>% 
  rename_with( ~ gsub("time", "_time", .x, fixed=T)) %>% 
  select(-chat) %>% 
  gather(key, value, starts_with('player')) %>% 
  separate(key, into = c('blah', 'playerId', 'info')) %>% 
  spread(info, value) %>% 
  select(-blah) %>% 
  mutate(tangram = gsub('/experiment/tangram_', '', target, fixed=TRUE),
         tangram = gsub('.png', '', tangram, fixed=TRUE)) %>% 
  mutate(correct=as.logical(correct),
         time=as.numeric(time)/1000) %>% 
  filter(!is.na(correct)) %>% 
  filter(playerId!=speaker)

#only include rounds that finished
rounds_exclude <- d.round_results.raw %>% group_by(gameId,numPlayers,repNum) %>% tally() %>% filter(n!=12*(numPlayers-1)) %>% select(gameId,repNum)

d.round_results <-  d.round_results.raw %>% anti_join(rounds_exclude)

```


```{r}
summary <- d.round_results %>% group_by(trialNum, repNum, gameId, numPlayers) %>% 
           mutate(time= time %|% 180) %>% 
  summarize(max_time=max(time)) %>% 
  group_by(gameId, numPlayers) %>% 
  summarize(total_time=sum(max_time)/60,
            num_rounds=max(repNum)) %>% 
  arrange(numPlayers)

knitr::kable(summary)

summary %>% filter(num_rounds==5) %>% group_by(numPlayers) %>% tally()

summary %>% filter(num_rounds!=5) %>% group_by(numPlayers) %>% tally()
```


<!--
<!-- # Demographics -->
<!-- ```{r demographics} -->
<!-- d.exit.survey <- read_csv(here(data_location, 'player-inputs.csv')) %>% -->
<!--   filter(createdAt >= date_start) %>%  -->
<!--   left_join(d.games, by = c('gameId')) %>%  -->
<!--     rename_with(~ gsub("data.", "", .x, fixed = TRUE)) -->

<!-- ``` -->

<!-- ```{r feedback} -->

<!-- d.exit.survey %>% select( language, fair, chatUseful, feedback, time) %>% knitr::kable() -->

<!-- ``` -->



# Pretty pictures


```{r chat}
d.chat <- d.chat.raw %>%
  #filter(role == 'speaker') %>%
  filter(!is.na(target)) %>% 
  mutate(text = gsub("\\n", '', fixed = T, text),
         text = gsub("[/?/.]", ' ', text),
         text = str_squish(text),
         tangram = gsub('/experiment/tangram_', '', target, fixed=TRUE),
         tangram = gsub('.png', '', tangram, fixed=TRUE),
         utt_length_chars = str_length(text), 
         utt_length_words = str_count(text, "\\W+") + 1) %>%
  group_by(gameId, trialNum, repNum, tangram, playerId, role, countCorrect, numPlayers) %>%
  summarize(text = paste0(text, collapse = ', '),
            total_num_words = sum(utt_length_words) %>% as.numeric(),
            total_num_chars = sum(utt_length_chars) %>% as.numeric()) %>%
  anti_join(rounds_exclude) %>% 
  full_join(d.round_results, c("gameId", "trialNum", "repNum", "playerId", "tangram", "countCorrect", "numPlayers")) %>% 
  mutate(text = text %|% "",
         total_num_words= total_num_words %|% 0,
         total_num_chars= total_num_chars %|% 0,
         role = role %|% "listener")

```

Everything here has bootstrapped 95% CIs.

```{r}
# ggplot(d.chat, aes(x=repNum, y=total_num_words, color=role))+
#   facet_wrap(~tangram, nrow=2)+
#   scale_color_brewer(palette="Dark2")+
#      stat_summary(fun.data = "mean_cl_boot")+
#   labs(title="Number of words", y="Number of words", x="Round number")+
#   theme(legend.position="bottom")

ggplot(d.chat, aes(x=repNum, y=total_num_words, color=as.factor(numPlayers)))+
  facet_wrap(~role, nrow=1)+
  scale_color_brewer(palette="Dark2")+
     stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width=.3))+
  labs(title="Number of words", y="Number of words", x="Round number")+
  theme(legend.position="bottom")



```

```{r accuracy}
d.round_results %>% group_by(playerId,repNum, gameId, numPlayers) %>% 
  summarize(pct_corr=sum(correct)) %>% 
  ggplot(aes(x=repNum, y=pct_corr, color=as.factor(numPlayers)))+
  stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width=.2))+
  #geom_point()+
  scale_color_brewer(palette="Dark2")+
  scale_y_continuous(breaks=c(0,3,6,9,12), limits = c(0,12))+
  labs(x="Round Number", y="Number correctly selected", title= "Overall accuracy increases over repetitions")

#ggsave(here(image_location, 'accuracy.pdf'), width=6, height=3)

```


```{r time}
d.round_results %>% group_by(playerId, repNum, gameId, numPlayers) %>% 
  filter(correct==T) %>% 
  #summarize(time=mean(time)) %>% 
  ggplot(aes(x=repNum, y=time, color=as.factor(numPlayers)))+
  #geom_jitter(width=.2, height=0, alpha=.1)+
      stat_summary(fun.data = "mean_cl_boot")+
  scale_y_continuous(limits = c(0,180))+
    scale_color_brewer(palette="Dark2")+
  labs(x="Round Number", y="Time to selection in seconds",
       title="People choose faster in later rounds")

#ggsave(here(image_location, 'time.pdf'), width=6, height=3)

```


```{r}
d.prev.speaker <- d.chat %>% ungroup() %>%  filter(role=="speaker") %>% select(gameId,repNum, tangram, total_num_words_prev=total_num_words)
d.prev.round <- d.chat %>% ungroup() %>% select(playerId, correct, tangram, gameId, repNum) %>% 
  left_join(d.prev.speaker) %>% unique() %>% mutate(repNum=repNum+1)


d.chat.lagged <- d.chat %>%
  ungroup() %>% 
  select(gameId, playerId, trialNum, repNum, playerId, role, tangram, total_num_words, numPlayers) %>%
  left_join(d.prev.round) %>%
  mutate(reduction_word=log(total_num_words)-log(total_num_words_prev)) %>%
  filter(repNum>0) %>%
  filter(role=="speaker") %>%
  mutate(prev_correct_round=correct)

ggplot(d.chat.lagged, aes(x=repNum, y=total_num_words, color=prev_correct_round))+
  facet_wrap(~numPlayers, nrow=1) +
    scale_color_brewer(palette="Dark2")+
      stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width=.2))+
    labs(title="Utterance length", y="Number of words", x="Round number")

ggplot(d.chat.lagged, aes(x=repNum, y=reduction_word, color=prev_correct_round))+
  facet_wrap(~numPlayers, nrow=1) +
    scale_color_brewer(palette="Dark2")+
      stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width=.2))+
    labs(title="Change in utterance length", y="Log change in words", x="Round number")

# ggplot(d.chat.lagged, aes(x=repNum, y=reduction_char, color=prev_correct_round))+
#   facet_wrap(~numPlayers, nrow=1) +
#     scale_color_brewer(palette="Dark2")+
#       stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width=.2))+
#     labs(title="Change in utterance length", y="Log change in  chars", x="Round number")
# 
# ggplot(d.chat.lagged, aes(x=repNum, y=reduction_word, color=prev_all_correct_round))+
#     scale_color_brewer(palette="Dark2")+
#       stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width=.2))+
#     labs(title="Change in utterance length", y="Log change in words", x="Round number")
# 
# ggplot(d.chat.lagged, aes(x=repNum, y=reduction_char, color=prev_all_correct_round))+
#     scale_color_brewer(palette="Dark2")+
#       stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width=.2))+
#     labs(title="Change in utterance length", y="Log change in  chars", x="Round number")
# 
# ggplot(d.chat.lagged, aes(x=repNum, y=reduction_word_trial, color=prev_correct_trial))+
#     facet_wrap(~numPlayers, nrow=1) +
#     scale_color_brewer(palette="Dark2")+
#       stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width=.2))+
#     labs(title="Change in utterance length next trial", y="Log change in words", x="Round number")
# 
# ggplot(d.chat.lagged, aes(x=repNum, y=reduction_char_trial, color=prev_correct_trial))+
#     facet_wrap(~numPlayers, nrow=1) +
#     scale_color_brewer(palette="Dark2")+
#       stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width=.2))+
#     labs(title="Change in utterance length next trial", y="Log change in  chars", x="Round number")

```
