---
title: "6p no rotate"
output:
  html_document: 
    toc: true
---



```{r set-up, include=F}
knitr::opts_chunk$set(echo = FALSE, warning=F, message=F)
knitr::opts_chunk$set(dev = "png", dev.args = list(type = "cairo-png"))
options(knitr.table.format = "html")
library(tidyverse)
library(jsonlite)
library(here)
library(rlang)
library(lme4)
library(brms)
library(rstan)
library(viridis)
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())
theme_set(theme_bw())

ParseJSONColumn <- function(x) {
  str_c("[ ", str_c(x, collapse = ",", sep=" "), " ]")  %>% 
    fromJSON(flatten = T)
}

##Data import constants
data_location="data/study2a"


date_start=lubridate::ymd('2022-03-30')

image_location="write-ups/images"

model_location="code/models"


```

```{r, include=F, eval=F}
##This was for determining participant bonuses using the version of data with PID
d.treatments <- read_csv(here(data_location, 'treatments.csv')) %>% rename(treatmentId=`_id`)
# 
d.games <- read_csv(here(data_location, 'games.csv')) %>%
  select(gameId=`_id`, treatmentId, playerIds) %>%
  left_join(d.treatments) %>%
  mutate(playerIds=str_split(playerIds,",")) %>%
  unnest(playerIds) %>%
  select(playerId=playerIds, name)

d.players <- read_csv(here(data_location, 'players.csv')) %>%
  filter(createdAt>lubridate::ymd('2022-04-03')) %>% 
  rename(playerId=`_id`) %>%
  left_join(d.games) %>%
  select(data.bonus, data.roleList, playerId,id,data.bonus,name) %>%
    filter(!is.na(name)) %>%
  mutate(is.speaker=ifelse(str_detect(data.roleList,"speaker"), 1,0),
                                      bonus=round(data.bonus+2*is.speaker,2),
         cost=round(bonus*4/3,2)) %>% select(-data.roleList) %>% write_csv(here(data_location, "player_payments.csv")) %>% select(id,bonus) %>% write_csv(here(data_location,"for_prolific.csv"))


```



```{r, include=F, eval=F}

d.games <- read_csv(here(data_location, 'games.csv')) %>% 
  rename(gameId = `_id`) %>% 
    filter(createdAt >= date_start)

d.chat.raw <- read_csv(here(data_location, 'rounds.csv'), guess_max=10000) %>%
  filter(createdAt >= date_start) %>%
  mutate(data.chat = ifelse(is.na(data.chat), '{}', data.chat)) %>%
  rename(row_id = `_id`) %>%
  mutate(data.chat = map(data.chat, .f = ParseJSONColumn)) %>%
  unnest(data.chat) %>%
  select(-data.target, -ends_with('response'), -ends_with('_correct'), -ends_with('time')) %>%
  rename_with(~ gsub("data.", "", .x, fixed = TRUE)) %>% 
  write_csv(here(data_location, 'raw_chat.csv'))

d.round_results.raw <- read_csv(here(data_location,'rounds.csv'),guess_max=10000) %>% 
  filter(createdAt >= date_start) %>% 
  rename_with(~ gsub("data.", "", .x, fixed = TRUE)) %>% 
  rename_with ( ~ gsub("room", "player", .x, fixed=T)) %>% 
    rename_with ( ~ gsub("player", "player_", .x, fixed=T)) %>% 
    rename_with ( ~ gsub("correct", "_correct", .x, fixed=T)) %>% 
    rename_with ( ~ gsub("response", "_response", .x, fixed=T)) %>% 
  rename_with( ~ gsub("time", "_time", .x, fixed=T)) %>% 
  select(-chat) %>% 
  gather(key, value, starts_with('player')) %>% 
  separate(key, into = c('blah', 'playerId', 'info')) %>% 
  spread(info, value) %>% 
  select(-blah) %>% 
  mutate(tangram = gsub('/experiment/tangram_', '', target, fixed=TRUE),
         tangram = gsub('.png', '', tangram, fixed=TRUE)) %>% 
  mutate(correct=as.logical(correct),
         time=as.numeric(time)/1000) %>% 
  filter(!is.na(correct)) %>% 
  filter(playerId!=speaker) %>% 
  write_csv(here(data_location, 'raw_results.csv'))

d.exit.survey <- read_csv(here(data_location, 'player-inputs.csv')) %>%
  filter(createdAt >= date_start) %>%
  left_join(d.games, by = c('gameId')) %>%
    rename_with(~ gsub("data.", "", .x, fixed = TRUE)) %>% 
    write_csv(here(data_location,'exit.csv'))


```

```{r}
#we exclude rounds where no one talked (this is our criteria for "they weren't playing anymore")
# this is better than if no one submitted b/c maybe people fail to click on some round?
rounds_include <- (read_csv(here(data_location,'raw_chat.csv'))) %>% 
  filter(!is.na(text)) %>%
  select(gameId,numPlayers,repNum,targetNum) %>% unique() %>% 
  group_by(gameId,numPlayers,repNum) %>% tally() %>% 
  filter(n==12) %>% select(gameId,repNum) %>% write_rds(here(data_location,"rounds_include.rds"))

d.round_results <-(read_csv(here(data_location,'raw_results.csv'))) %>% inner_join(rounds_include) %>% write_rds(here(data_location,'round_results.rds'))

d.correct <- d.round_results %>% 
  group_by(`_id`,gameId,target,targetNum,repNum,trialNum,
           numPlayers,countCorrect,speaker,tangram) %>% 
  summarize(realCorrect=sum(ifelse(correct,1,0)))

d.round_results %>% left_join(d.correct) %>% write_rds(here(data_location,"round_results.rds"))

d.exit_survey <- (read_csv(here(data_location,'exit.csv'))) %>% 
  write_csv(here(data_location,"exit_survey.csv"))
  
```
How many games

```{r}
d.round_results %>% group_by(gameId, numPlayers) %>% 
  summarize(max_rep=max(repNum)) %>% 
  mutate(game_length=ifelse(max_rep==5,"complete","partial")) %>% 
  group_by(numPlayers, game_length) %>% 
  tally() %>% 
  pivot_wider(names_from="game_length",values_from="n")
```

How long full games took

```{r}
summary <- d.round_results %>% group_by(trialNum, repNum, gameId, numPlayers) %>% 
           mutate(time= time %|% 180) %>% 
  summarize(max_time=max(time)) %>% 
  group_by(gameId, numPlayers) %>% 
  summarize(total_time=sum(max_time)/60,
            num_rounds=max(repNum)) %>% 
  arrange(numPlayers)

message("Full games")

summary %>% filter(num_rounds==5) %>% 
  group_by(numPlayers) %>% 
  summarize(games=n(),
            min_time=min(total_time) %>% round(),
            `25th_time`=quantile(total_time, .25)%>% round(),
            median_time=quantile(total_time, .5)%>% round(),
            `75th_time`=quantile(total_time, .75)%>% round(),
            max_time=max(total_time)%>% round()) 

```





# Pretty pictures


```{r chat}

rounds_include <- read_rds(here(data_location,"rounds_include.rds"))
d.round_results <- read_rds(here(data_location,"round_results.rds"))
d.chat.filter <- read_csv(here(data_location, "filtered_chat.csv")) %>% 
  filter(!is.chitchat) %>% 
  filter(!is.na(target)) %>% 
  mutate(text = gsub("\\n", '', fixed = T, spellchecked), # note that this is using spellcorrected version!!!!
         text = gsub("[/?/.]", ' ', text),
         text = str_squish(text),
         tangram = gsub('/experiment/tangram_', '', target, fixed=TRUE),
         tangram = gsub('.png', '', tangram, fixed=TRUE),
         utt_length_chars = str_length(text), 
         utt_length_words = str_count(text, "\\W+") + 1) %>%
  group_by(gameId, trialNum, repNum, tangram) %>% 
  mutate(is.firstutter=ifelse(role!="speaker",F,NA)) %>% 
  fill(c("is.firstutter"), .direction="down") %>% 
  mutate(is.firstutter= is.firstutter %|% T) 

d.chat <- d.chat.filter %>% 
  group_by(gameId, trialNum, repNum, tangram, playerId, role, numPlayers) %>%
  summarize(text = paste0(text, collapse = ', '),
            total_num_words = sum(utt_length_words, na.rm=T) %>% as.numeric(),
            total_num_chars = sum(utt_length_chars, na.rm=T) %>% as.numeric()) %>%
  inner_join(rounds_include) %>% 
  full_join(d.round_results, c("gameId", "trialNum", "repNum", "playerId", "tangram", "numPlayers")) %>% 
  mutate(text = text %|% "",
         total_num_words= total_num_words %|% 0,
         total_num_chars= total_num_chars %|% 0,
         role = role %|% "listener")

d.chat.pre <- d.chat.filter %>% group_by(gameId, trialNum, repNum, tangram, playerId, is.firstutter,role, numPlayers) %>%
  summarize(text = paste0(text, collapse = ', '),
            total_num_words = sum(utt_length_words, na.rm=T) %>% as.numeric(),
            total_num_chars = sum(utt_length_chars, na.rm=T) %>% as.numeric()) %>%
  inner_join(rounds_include) %>% 
  ungroup() %>% 
  mutate(text = text %|% "",
         total_num_words= total_num_words %|% 0,
         total_num_chars= total_num_chars %|% 0,
         role = role %|% "listener") %>% 
  filter(is.firstutter)

```

```{r rotate-data}
rotate_data_loc <- "data/study1"

ro_rounds_include <- read_rds(here(rotate_data_loc,"rounds_include.rds")) 
rod.round_results <- read_rds(here(rotate_data_loc,"round_results.rds")) %>% mutate(rotate="rotate")
rod.chat.filter <- read_csv(here(rotate_data_loc, "filtered_chat.csv")) %>% 
  filter(!is.chitchat) %>% 
  filter(!is.na(target)) %>% 
  mutate(text = gsub("\\n", '', fixed = T, spellchecked), # note that this is using spellcorrected version!!!!
         text = gsub("[/?/.]", ' ', text),
         text = str_squish(text),
         tangram = gsub('/experiment/tangram_', '', target, fixed=TRUE),
         tangram = gsub('.png', '', tangram, fixed=TRUE),
         utt_length_chars = str_length(text), 
         utt_length_words = str_count(text, "\\W+") + 1) %>%
  group_by(gameId, trialNum, repNum, tangram) %>% 
  mutate(is.firstutter=ifelse(role!="speaker",F,NA)) %>% 
  fill(c("is.firstutter"), .direction="down") %>% 
  mutate(is.firstutter= is.firstutter %|% T) 

rod.chat <- rod.chat.filter %>% 
  group_by(gameId, trialNum, repNum, tangram, playerId, role, numPlayers) %>%
  summarize(text = paste0(text, collapse = ', '),
            total_num_words = sum(utt_length_words, na.rm=T) %>% as.numeric(),
            total_num_chars = sum(utt_length_chars, na.rm=T) %>% as.numeric()) %>%
  inner_join(ro_rounds_include) %>% 
  full_join(rod.round_results, c("gameId", "trialNum", "repNum", "playerId", "tangram", "numPlayers")) %>% 
  mutate(text = text %|% "",
         total_num_words= total_num_words %|% 0,
         total_num_chars= total_num_chars %|% 0,
         role = role %|% "listener") %>% mutate(rotate="rotate")

combined_results <- d.round_results %>% mutate(rotate="single") %>% union(rod.round_results) %>% filter(numPlayers==6)
combined_chat <- d.chat %>% mutate(rotate="single") %>% union(rod.chat) %>% filter(numPlayers==6)
```


Everything here has bootstrapped 95% CIs. 

Should find better curves to fit, but using quadratic to allow for some curvature.

```{r}

ggplot(combined_chat, aes(x=repNum, y=total_num_words, color=rotate))+
  facet_wrap(~role, nrow=1)+
  scale_color_brewer(palette="Dark2")+
    geom_jitter(alpha=.05)+
    geom_smooth(method=glm, formula=y~poly(x,2), alpha=.3)+
  #geom_smooth(method = "glm", formula = y~x,method.args = list(family = gaussian(link = 'log')))+
     stat_summary(fun.data = "mean_cl_boot")+
    scale_y_continuous(limits = c(0,50))+
  labs(title="Number of words", y="Number of words", x="Round number", color="Player count")+
  theme(legend.position="bottom")


ggplot(combined_chat, aes(x=repNum, y=total_num_words, color=rotate))+
  facet_wrap(~role, nrow=1)+
  scale_color_brewer(palette="Dark2")+
    geom_smooth(method=glm, formula=y~poly(x,2), alpha=.3)+
  #geom_smooth(method = "glm", formula = y~x,method.args = list(family = gaussian(link = 'log')))+
     stat_summary(fun.data = "mean_cl_boot")+
  labs(title="Number of words", y="Number of words", x="Round number", color="Player count")+
  theme(legend.position="bottom")
```



```{r}
combined_chat %>% filter(role=="speaker") %>% 
    mutate(groupxtangram=str_c(gameId,tangram)) %>% 
  group_by(repNum, numPlayers, gameId,tangram, groupxtangram, rotate) %>% 
  summarize(words=sum(total_num_words)) %>% 
ggplot(aes(x=repNum, y=words, color=rotate))+
  facet_wrap(~rotate, nrow=1)+
  scale_color_brewer(palette="Dark2")+
    geom_line(aes(group=groupxtangram), alpha=.1,method=glm, se=F)+
    #geom_smooth(method = "glm", formula = y~x,method.args = list(family = gaussian(link = 'log')))+
    geom_smooth(method=glm, formula=y~poly(x,2), alpha=.3)+
  labs(title="Words from speaker per tangram", y="Number of words", x="Round number", color="Player count")+
  theme(legend.position="null")


```

```{r}
combined_chat %>% filter(role=="speaker") %>% 
ggplot(aes(x=repNum, y=total_num_words, color=rotate))+
  facet_wrap(~tangram)+
  scale_color_brewer(palette="Dark2")+
    geom_smooth(method=glm, formula=y~poly(x,2), se=T, alpha=.1)+
    #  geom_smooth(method = "glm", formula = y~x,method.args = list(family = gaussian(link = 'log')))+
       stat_summary(fun.data = "mean_cl_boot", size=.2)+
  labs(title="Tangram variability", y="Number of words", x="Round number", color="Player count")+
  theme(legend.position="bottom")


```



```{r accuracy}
combined_results %>% group_by(playerId,repNum, gameId, numPlayers, rotate) %>% 
  mutate(correct.num=ifelse(correct,1,0)) %>% 
  ggplot(aes(x=repNum, y=correct.num, color=rotate))+
geom_smooth(method = "glm", method.args = list(family = "binomial")) + 
  stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width=.2))+
  #geom_point()+
  scale_color_brewer(palette="Dark2")+
  #scale_y_continuous(limits = c(0,1))+
  labs(x="Round Number", y="Fraction correctly selected", title= "Overall accuracy increases over repetitions", color="Player count")+
    theme(legend.position="bottom")



```

```{r time}
combined_results %>% group_by(playerId, repNum, gameId, numPlayers, rotate) %>% 
  filter(correct==T) %>% 
  #summarize(time=mean(time)) %>% 
  ggplot(aes(x=repNum, y=time, color=rotate))+
  geom_jitter(width=.4, height=0, alpha=.03)+
geom_smooth(method = "glm", formula = y~x,
                      method.args = list(family = gaussian(link = 'log')))+
  stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width=.2))+
  scale_y_continuous(limits = c(0,180))+
    scale_color_brewer(palette="Dark2")+
  labs(x="Round Number", y="Time to selection in seconds",
       title="People choose faster in later rounds", color="Player count")+
  theme(legend.position = "bottom")


```
