//the data as string .. was generated by the code below:

export const taskData = [
    {
        _id: "0",
        target: "/experiment/tangram_A.png"
    },
    {
        _id: "1",
        target: "/experiment/tangram_B.png"
    },
    {
        _id: "2",
        target: "/experiment/tangram_C.png"
    },
    {
        _id: "3",
        target: "/experiment/tangram_D.png"
    },
];
